const TOTAL_STEPS=13;
const AVATARS=["👤","⚔","👑","🔥","✨","🎯","💪","🌌","🐉","⚡","🏔","🌑"];
const ACHIEVEMENTS=[
{id:"first_quest",icon:"⚔",name:"First Quest"},
{id:"streak3",icon:"🔥",name:"3-Day Streak"},
{id:"streak7",icon:"🔥",name:"7-Day Streak"},
{id:"rank_d",icon:"↑",name:"D-Rank"},
{id:"rank_c",icon:"↑",name:"C-Rank"},
{id:"first_boss",icon:"🐉",name:"Boss Clear"},
{id:"workouts10",icon:"💪",name:"10 Workouts"},
{id:"skill_up",icon:"✦",name:"Skill Up"}
];
const RANKS=[{rank:"E",min:1,title:"Novice Hunter",msg:"You have taken the first step."},{rank:"D",min:5,title:"Apprentice Hunter",msg:"Your body is beginning to adapt."},{rank:"C",min:12,title:"Trusted Hunter",msg:"Consistency is becoming your strength."},{rank:"B",min:22,title:"Elite Hunter",msg:"Few reach this level of discipline."},{rank:"A",min:35,title:"High-Rank Hunter",msg:"Your presence is growing."},{rank:"S",min:50,title:"Shadow Commander",msg:"You now stand among the strongest."}];
const SKILLS={pushup:{name:"Push-up Path",need:3,levels:[{name:"Wall Push-ups",tip:"Keep body straight.",mistake:"Avoid bending at hips."},{name:"Knee Push-ups",tip:"Hands under shoulders.",mistake:"Avoid hip sag."},{name:"Full Push-ups",tip:"Straight line head to heels.",mistake:"Avoid flaring elbows."},{name:"Diamond Push-ups",tip:"Hands in diamond.",mistake:"Avoid shrugging."},{name:"Archer Push-ups",tip:"Shift weight to one arm.",mistake:"Avoid twisting hips."},{name:"Pseudo Planche Lean",tip:"Lean forward, straight arms.",mistake:"Avoid bending elbows."}]},squat:{name:"Squat Path",need:3,levels:[{name:"Assisted Squats",tip:"Sit back as into a chair.",mistake:"Avoid knees collapsing."},{name:"Bodyweight Squats",tip:"Knees track over toes.",mistake:"Avoid rising on toes."},{name:"Jump Squats",tip:"Land softly.",mistake:"Avoid locked knees."},{name:"Bulgarian Split Squats",tip:"Front knee over ankle.",mistake:"Avoid knee too far forward."},{name:"Shrimp Squat Progress",tip:"Lower with control.",mistake:"Avoid rushing."},{name:"Pistol Squat Progress",tip:"Use support while building.",mistake:"Avoid knee collapse."}]},core:{name:"Core Path",need:3,levels:[{name:"Knee Plank",tip:"Hips level.",mistake:"Avoid lower back sag."},{name:"Full Plank",tip:"Straight body, breathe.",mistake:"Avoid holding breath."},{name:"Side Plank",tip:"Keep hips high.",mistake:"Avoid rotating hip."},{name:"Hollow Hold",tip:"Lower back pressed down.",mistake:"Avoid arching."},{name:"L-Sit Progress",tip:"Chest tall, lift legs.",mistake:"Avoid rounded shoulders."},{name:"Dragon Flag Progress",tip:"Body rigid.",mistake:"Avoid bending only at hips."}]},pull:{name:"Pull Path",need:3,levels:[{name:"Scapular Pulls",tip:"Pull shoulder blades down.",mistake:"Avoid using arms."},{name:"Australian Pull-ups",tip:"Chest to bar, body straight.",mistake:"Avoid hip sag."},{name:"Negative Pull-ups",tip:"Lower slowly.",mistake:"Avoid dropping fast."},{name:"Pull-ups",tip:"Chin over bar, control down.",mistake:"Avoid swinging."},{name:"Chest-to-Bar",tip:"Chest near bar.",mistake:"Avoid stopping at chin."},{name:"Archer Pull-ups",tip:"Pull to one side.",mistake:"Avoid rotating body."}]}};
const WORKOUTS=[{id:"e1",rank:"E",name:"First Steps",time:"12 min",xp:50,ex:[{n:"Jumping Jacks",s:2,r:20,u:"reps"},{n:"Knee Push-ups",s:2,r:8,u:"reps"},{n:"Bodyweight Squats",s:2,r:12,u:"reps"},{n:"Knee Plank",s:2,r:20,u:"sec"}]},{id:"e2",rank:"E",name:"Shadow Warm-up",time:"14 min",xp:55,ex:[{n:"High Knees",s:3,r:25,u:"sec"},{n:"Glute Bridges",s:3,r:12,u:"reps"},{n:"Crunches",s:2,r:15,u:"reps"},{n:"Wall Sit",s:2,r:25,u:"sec"}]},{id:"d1",rank:"D",name:"Gate Clear",time:"18 min",xp:85,ex:[{n:"Push-ups",s:3,r:12,u:"reps"},{n:"Squats",s:3,r:15,u:"reps"},{n:"Lunges",s:2,r:10,u:"reps"},{n:"Mountain Climbers",s:3,r:20,u:"reps"},{n:"Plank",s:2,r:35,u:"sec"}]},{id:"d2",rank:"D",name:"Hunter Drill",time:"20 min",xp:95,ex:[{n:"Burpees",s:3,r:8,u:"reps"},{n:"Diamond Push-ups",s:3,r:8,u:"reps"},{n:"Jump Squats",s:3,r:12,u:"reps"},{n:"Russian Twists",s:3,r:20,u:"reps"},{n:"Side Plank",s:2,r:25,u:"sec"}]},{id:"c1",rank:"C",name:"Double Gate",time:"25 min",xp:140,ex:[{n:"Push-ups",s:4,r:15,u:"reps"},{n:"Pike Push-ups",s:3,r:10,u:"reps"},{n:"Lunges",s:3,r:12,u:"reps"},{n:"Burpees",s:3,r:10,u:"reps"},{n:"Leg Raises",s:3,r:12,u:"reps"},{n:"Plank",s:3,r:45,u:"sec"}]},{id:"b1",rank:"B",name:"Elite Trial",time:"30 min",xp:200,ex:[{n:"Push-ups",s:4,r:20,u:"reps"},{n:"Diamond Push-ups",s:3,r:12,u:"reps"},{n:"Jump Squats",s:4,r:15,u:"reps"},{n:"Burpees",s:4,r:12,u:"reps"},{n:"Mountain Climbers",s:3,r:30,u:"reps"},{n:"Plank",s:3,r:60,u:"sec"}]},{id:"a1",rank:"A",name:"High Rank Protocol",time:"35 min",xp:280,ex:[{n:"Push-ups",s:5,r:25,u:"reps"},{n:"Pike Push-ups",s:4,r:12,u:"reps"},{n:"Jump Squats",s:4,r:20,u:"reps"},{n:"Burpees",s:4,r:15,u:"reps"},{n:"Lunges",s:3,r:15,u:"reps"},{n:"Plank",s:3,r:75,u:"sec"}]},{id:"s1",rank:"S",name:"Shadow Commander",time:"45 min",xp:450,ex:[{n:"Push-ups",s:5,r:30,u:"reps"},{n:"Diamond Push-ups",s:4,r:15,u:"reps"},{n:"Pike Push-ups",s:4,r:15,u:"reps"},{n:"Jump Squats",s:5,r:25,u:"reps"},{n:"Burpees",s:5,r:18,u:"reps"},{n:"Mountain Climbers",s:4,r:40,u:"reps"},{n:"Plank",s:4,r:90,u:"sec"}]}];
const BOSSES=[{id:"boss1",name:"Iron Fortress",desc:"High volume strength test.",xp:320,ex:[{n:"Push-ups",s:5,r:20,u:"reps"},{n:"Squats",s:5,r:25,u:"reps"},{n:"Plank",s:4,r:45,u:"sec"},{n:"Burpees",s:4,r:12,u:"reps"}]},{id:"boss2",name:"Shadow Legion",desc:"Endurance gauntlet.",xp:340,ex:[{n:"Jumping Jacks",s:4,r:40,u:"reps"},{n:"Mountain Climbers",s:4,r:30,u:"reps"},{n:"High Knees",s:4,r:40,u:"sec"},{n:"Burpees",s:4,r:15,u:"reps"}]},{id:"boss3",name:"Monarch's Trial",desc:"Full-body raid.",xp:420,ex:[{n:"Push-ups",s:4,r:25,u:"reps"},{n:"Jump Squats",s:4,r:20,u:"reps"},{n:"Diamond Push-ups",s:3,r:12,u:"reps"},{n:"Lunges",s:3,r:15,u:"reps"},{n:"Plank",s:3,r:60,u:"sec"}]}];
const PROGRAMS=[{id:"p1",name:"Foundation",weeks:2,desc:"Build the basics.",sessions:["e1","e2","d1"]},{id:"p2",name:"Strength Builder",weeks:3,desc:"Push, squat and core.",sessions:["d1","d2","c1"]},{id:"p3",name:"Hunter Path",weeks:4,desc:"Progressive challenge.",sessions:["c1","b1","a1"]}];
const MISSIONS=[{id:"m1",name:"Forest Scout",mins:30,coins:15,ess:2,xp:25},{id:"m2",name:"Gate Patrol",mins:60,coins:35,ess:5,xp:50},{id:"m3",name:"Shadow Hunt",mins:120,coins:70,ess:12,xp:90}];

let S={name:"",avatar:"👤",bio:"",level:1,xp:0,totalXP:0,coins:0,essence:0,stats:{str:10,end:10,agi:10,vit:10},fit:"beginner",goal:"balanced",weekFocus:"balanced",profile:{},skills:{pushup:{level:0,practice:0},squat:{level:0,practice:0},core:{level:0,practice:0},pull:{level:0,practice:0}},quests:[],doneToday:[],history:[],streak:0,lastDay:null,workouts:0,questsDone:0,weekly:null,bossCleared:[],prs:{},activity:{},exCount:{},woCount:{},achievements:[],activeProgram:null,mission:null,lastHardDay:null,created:null};
let cur=null,OB={areas:[]},restSeconds=90,restInterval=null,restRunning=false;

function save(){try{localStorage.setItem("arise_v11",JSON.stringify(S))}catch(e){}}
function load(){const raw=localStorage.getItem("arise_v11")||localStorage.getItem("arise_v10")||localStorage.getItem("arise_v9");if(!raw)return false;try{const d=JSON.parse(raw);S={...S,...d};if(!S.skills)S.skills={pushup:{level:0,practice:0},squat:{level:0,practice:0},core:{level:0,practice:0},pull:{level:0,practice:0}};if(S.coins==null)S.coins=0;if(S.essence==null)S.essence=0;if(!S.prs)S.prs={};if(!S.activity)S.activity={};if(!S.bossCleared)S.bossCleared=[];if(!S.profile)S.profile={};if(!S.exCount)S.exCount={};if(!S.woCount)S.woCount={};if(!S.achievements)S.achievements=[];if(!S.avatar)S.avatar="👤";if(S.bio==null)S.bio="";return true}catch(e){return false}}
function xpNeed(lv){return Math.floor(100*Math.pow(1.28,lv-1))}
function getRank(lv){let r=RANKS[0];for(const x of RANKS)if(lv>=x.min)r=x;return r}
function today(){return new Date().toISOString().slice(0,10)}
function weekKey(){const d=new Date(),onejan=new Date(d.getFullYear(),0,1),week=Math.ceil((((d-onejan)/86400000)+onejan.getDay()+1)/7);return d.getFullYear()+"-W"+week}
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove("show"),2800)}
function system(msg){document.getElementById("systemMsg").innerHTML=`<strong>[SYSTEM]</strong> ${msg}`}
function unlockAch(id){if(S.achievements.includes(id))return;S.achievements.push(id);save();const a=ACHIEVEMENTS.find(x=>x.id===id);if(a)toast("Achievement · "+a.name)}

function sel(btn){const k=btn.dataset.k,v=btn.dataset.v;btn.parentElement.querySelectorAll(`.choice[data-k="${k}"]`).forEach(b=>b.classList.remove("selected"));btn.classList.add("selected");OB[k]=v;const nextBtn=document.getElementById("n"+(parseInt(btn.closest(".step").id.slice(1))));if(nextBtn)nextBtn.disabled=false}
function selMulti(btn){const v=btn.dataset.v;btn.classList.toggle("selected");if(btn.classList.contains("selected")){if(!OB.areas.includes(v))OB.areas.push(v)}else{OB.areas=OB.areas.filter(a=>a!==v)}document.getElementById("n9").disabled=OB.areas.length===0}
function go(n){if(n===2){const name=document.getElementById("nameInput").value.trim();if(!name){toast("Enter a name");return}OB.name=name}document.querySelectorAll(".step").forEach(s=>s.classList.remove("active"));document.getElementById("s"+n).classList.add("active");document.getElementById("obBar").style.width=Math.round(n/TOTAL_STEPS*100)+"%"}

function finishOnboard(){S.name=OB.name;S.fit=OB.fit||"beginner";S.goal=OB.goal||"balanced";S.weekFocus=OB.goal||"balanced";S.profile={activity:OB.activity,equip:OB.equip,location:OB.location,duration:OB.duration,days:OB.days,areas:OB.areas||[],strength:+OB.strength||2,mobility:+OB.mobility||2,cardio:+OB.cardio||2,motive:OB.motive};S.created=Date.now();S.lastDay=today();S.streak=1;
const base={beginner:8,intermediate:14,advanced:20}[S.fit]||10;
S.stats={str:Math.max(5,base+((+OB.strength||2)-2)*3),end:Math.max(5,base+((+OB.cardio||2)-2)*3),agi:Math.max(5,base+((+OB.mobility||2)-2)*2),vit:base};
S.coins=10;S.essence=1;makeQuests();makeWeekly();save();
document.getElementById("onboard").classList.add("hidden");render();
system(`Hunter ${S.name} registered. Path calibrated.`);toast("System online")}

function makeQuests(){const day=today();if(S.lastDay===day&&S.quests.length)return;if(S.lastDay&&S.lastDay!==day){const y=new Date();y.setDate(y.getDate()-1);const yk=y.toISOString().slice(0,10);if(S.lastDay===yk&&S.doneToday.length)S.streak++;else if(S.lastDay!==yk)S.streak=1;S.doneToday=[]}S.lastDay=day;const r=getRank(S.level).rank,order=["E","D","C","B","A","S"],idx=order.indexOf(r);const pool=WORKOUTS.filter(w=>{const i=order.indexOf(w.rank);return i>=Math.max(0,idx-1)&&i<=Math.min(5,idx+1)});const main=pool[Math.floor(Math.random()*pool.length)]||WORKOUTS[0];let goalQ={strength:{name:"Strength Gate",desc:"40 total push-ups",xp:40},endurance:{name:"Endurance Gate",desc:"3 min cardio moves",xp:40},balanced:{name:"Balanced Hunt",desc:"Finish any ranked workout",xp:35},skill:{name:"Skill Practice",desc:"Log practice on any Skill Path",xp:35}}[S.goal]||{name:"Daily Duty",desc:"Complete one ranked workout",xp:35};S.quests=[{id:"q1",type:"workout",name:main.name,desc:main.time+" · "+main.rank+"-Rank",xp:main.xp,wid:main.id,done:false},{id:"q2",type:"simple",name:goalQ.name,desc:goalQ.desc,xp:goalQ.xp,done:false},{id:"q3",type:"simple",name:"Core Stabilization",desc:"Plank total 90 seconds",xp:30,done:false},{id:"q4",type:"simple",name:"Volume Protocol",desc:"50 squats or 35 push-ups",xp:30,done:false}];save()}
function completeQuest(id){const q=S.quests.find(x=>x.id===id);if(!q||q.done)return;q.done=true;S.doneToday.push(id);S.questsDone++;addXP(q.xp,q.name);S.coins+=Math.floor(q.xp/10)+3;S.essence+=1;S.stats.vit++;S.stats.end++;unlockAch("first_quest");if(S.streak>=3)unlockAch("streak3");if(S.streak>=7)unlockAch("streak7");save();render();toast(`Quest cleared · +${q.xp} XP`);system(`Quest “${q.name}” completed.`)}
function makeWeekly(){const wk=weekKey();if(S.weekly&&S.weekly.week===wk)return;const need=S.profile&&S.profile.days?Math.min(6,Math.max(3,+S.profile.days+1)):4;S.weekly={week:wk,name:"Weekly Shadow Task",desc:`Complete ${need} ranked workouts this week`,need,progress:0,xp:220,done:false};save()}
function updateWeekly(){if(!S.weekly||S.weekly.done)return;S.weekly.progress=Math.min(S.weekly.need,(S.weekly.progress||0)+1);if(S.weekly.progress>=S.weekly.need){S.weekly.done=true;addXP(S.weekly.xp,"Weekly Challenge");S.coins+=40;S.essence+=8;toast("Weekly Challenge cleared");system("Weekly Shadow Task complete.")}save()}
function setWeekFocus(f){S.weekFocus=f;save();render();toast("Focus updated")}

function practiceSkill(key){const sk=S.skills[key],def=SKILLS[key];if(sk.level>=def.levels.length-1){toast("Path complete");return}sk.practice++;addXP(15,def.name+" practice");S.coins+=2;S.stats.str++;if(key==="core")S.stats.vit++;if(key==="pull"||key==="pushup")S.stats.agi++;save();render();toast("Practice logged")}
function skillUp(key){const sk=S.skills[key],def=SKILLS[key];if(sk.level>=def.levels.length-1){toast("Max level");return}if(sk.practice<def.need){toast(`Practice ${def.need-sk.practice} more`);return}sk.level++;sk.practice=0;addXP(40,def.name+" advanced");S.coins+=10;S.essence+=2;S.stats.str+=2;S.stats.agi++;unlockAch("skill_up");save();render();toast("Skill advanced");system(`${def.name} advanced.`)}

function openWorkout(id,isBoss){const w=isBoss?BOSSES.find(b=>b.id===id):WORKOUTS.find(x=>x.id===id);if(!w)return;cur=JSON.parse(JSON.stringify(w));cur.isBoss=!!isBoss;cur.ex.forEach(e=>e.logged=0);document.getElementById("mTitle").textContent=w.name;document.getElementById("mSub").textContent=(w.rank?w.rank+"-Rank · ":"Boss · ")+(w.time||"")+" · +"+w.xp+" XP";updateProg();const box=document.getElementById("mEx");box.innerHTML="";cur.ex.forEach((e,i)=>{const div=document.createElement("div");div.className="ex";div.id="ex"+i;div.innerHTML=`<div><div class="ex-name">${e.n}</div><div class="ex-meta">${e.s} sets × ${e.r} ${e.u}</div></div><div class="log"><button onclick="logSet(${i},-1)">−</button><span id="log${i}">0</span><button onclick="logSet(${i},1)">+</button></div>`;box.appendChild(div)});document.getElementById("modal").classList.add("show");showRestTimer();restSeconds=90;updateRestDisplay()}
function logSet(i,d){if(!cur)return;const e=cur.ex[i];e.logged=Math.max(0,Math.min(e.s,e.logged+d));document.getElementById("log"+i).textContent=e.logged;document.getElementById("ex"+i).classList.toggle("done",e.logged>=e.s);updateProg()}
function markAll(){if(!cur)return;cur.ex.forEach((e,i)=>{e.logged=e.s;document.getElementById("log"+i).textContent=e.s;document.getElementById("ex"+i).classList.add("done")});updateProg()}
function updateProg(){if(!cur)return;const tot=cur.ex.reduce((a,e)=>a+e.s,0),log=cur.ex.reduce((a,e)=>a+e.logged,0);document.getElementById("mProg").style.width=(tot?Math.round(log/tot*100):0)+"%"}
function closeModal(){document.getElementById("modal").classList.remove("show");cur=null}
function finishWorkout(){if(!cur)return;const tot=cur.ex.reduce((a,e)=>a+e.s,0),log=cur.ex.reduce((a,e)=>a+e.logged,0);if(log<Math.ceil(tot*.4)){toast("Log at least 40% of sets");return}const gain=Math.floor(cur.xp*(log/tot));addXP(gain,cur.name);S.workouts++;S.lastHardDay=today();S.coins+=Math.floor(gain/8)+5;S.essence+=cur.isBoss?5:2;markActivity();updatePRs(cur);if(!S.woCount)S.woCount={};S.woCount[cur.name]=(S.woCount[cur.name]||0)+1;cur.ex.forEach(e=>{if(!S.exCount)S.exCount={};S.exCount[e.n]=(S.exCount[e.n]||0)+e.logged;const n=e.n.toLowerCase();if(n.includes("push")||n.includes("squat")||n.includes("lunge"))S.stats.str++;if(n.includes("burpee")||n.includes("jump")||n.includes("mountain")||n.includes("high"))S.stats.end++;if(n.includes("plank")||n.includes("crunch")||n.includes("leg")||n.includes("twist"))S.stats.vit++});Object.keys(S.stats).forEach(k=>S.stats[k]=Math.min(999,S.stats[k]));const match=S.quests.find(q=>q.wid===cur.id&&!q.done);if(match){match.done=true;S.doneToday.push(match.id);S.questsDone++;unlockAch("first_quest")}if(cur.isBoss){if(!S.bossCleared.includes(cur.id))S.bossCleared.push(cur.id);unlockAch("first_boss");system(`Boss “${cur.name}” cleared.`)}else updateWeekly();if(S.workouts>=10)unlockAch("workouts10");if(S.streak>=3)unlockAch("streak3");if(S.streak>=7)unlockAch("streak7");save();closeModal();render();toast(`+${gain} XP`)}

function addXP(amount,source){S.xp+=amount;S.totalXP+=amount;S.history.unshift({t:new Date().toLocaleString(),s:source,x:amount});if(S.history.length>40)S.history.pop();let up=false;const oldRank=getRank(S.level).rank;while(S.xp>=xpNeed(S.level)){S.xp-=xpNeed(S.level);S.level++;up=true;S.stats.str+=2;S.stats.end+=2;S.stats.agi+=2;S.stats.vit+=2;S.coins+=20;S.essence+=3}save();if(up){const r=getRank(S.level);document.getElementById("levelupText").textContent=`Level ${S.level} · ${r.title}`;document.getElementById("levelup").classList.add("show");system(r.msg+` You are now ${r.title}.`);if(r.rank!==oldRank){setTimeout(()=>toast(`Rank up · ${r.rank}-Rank`),400);if(r.rank==="D")unlockAch("rank_d");if(r.rank==="C")unlockAch("rank_c")}}}
function closeLevelup(){document.getElementById("levelup").classList.remove("show");render()}

function showRestTimer(){const el=document.getElementById("restTimer");if(el)el.style.display="block";updateRestDisplay()}
function updateRestDisplay(){const m=Math.floor(restSeconds/60).toString().padStart(2,"0"),s=(restSeconds%60).toString().padStart(2,"0");const el=document.getElementById("restTime");if(el)el.textContent=m+":"+s}
function adjustRest(d){restSeconds=Math.max(15,Math.min(300,restSeconds+d));if(!restRunning)updateRestDisplay()}
function toggleRest(){if(restRunning){clearInterval(restInterval);restRunning=false;const btn=document.querySelector("#restTimer .btn-primary");if(btn)btn.textContent="Start"}else{restRunning=true;const btn=document.querySelector("#restTimer .btn-primary");if(btn)btn.textContent="Pause";restInterval=setInterval(()=>{restSeconds--;updateRestDisplay();if(restSeconds<=0){clearInterval(restInterval);restRunning=false;restSeconds=90;updateRestDisplay();if(btn)btn.textContent="Start";toast("Rest complete");if(navigator.vibrate)navigator.vibrate(200)}},1000)}}

function updatePRs(workout){if(!S.prs)S.prs={};workout.ex.forEach(e=>{const key=e.n.toLowerCase(),volume=e.logged*(e.r||1);if(!S.prs[key]||volume>S.prs[key].volume)S.prs[key]={name:e.n,sets:e.logged,reps:e.r,volume,date:today()}})}
function renderPRs(){const el=document.getElementById("prList");if(!el)return;if(!S.prs||!Object.keys(S.prs).length){el.innerHTML='<div class="empty">Complete workouts to set records</div>';return}const sorted=Object.values(S.prs).sort((a,b)=>b.volume-a.volume).slice(0,8);el.innerHTML=sorted.map(p=>`<div class="pr-row"><div class="pr-name">${p.name}</div><div class="pr-value">${p.sets}×${p.reps}</div></div>`).join("")}
function renderCalendar(){const el=document.getElementById("calGrid");if(!el)return;if(!S.activity)S.activity={};const days=[];for(let i=27;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);days.push(d.toISOString().slice(0,10))}const todayKey=today();el.innerHTML=days.map(key=>{const active=S.activity[key]?"active":"",isToday=key===todayKey?"today":"";return `<div class="cal-day ${active} ${isToday}">${parseInt(key.slice(8),10)}</div>`}).join("")}
function markActivity(){if(!S.activity)S.activity={};S.activity[today()]=true;const keys=Object.keys(S.activity).sort();if(keys.length>60)keys.slice(0,keys.length-60).forEach(k=>delete S.activity[k])}
function renderPrograms(){const el=document.getElementById("programList");if(!el)return;el.innerHTML=PROGRAMS.map(p=>{const active=S.activeProgram===p.id;return `<div class="item ${active?"done":""}"><div class="item-row"><div class="item-name">${p.name}</div><div class="item-xp">${p.weeks} weeks</div></div><div class="item-desc">${p.desc}</div><button class="${active?"btn-secondary":"btn-primary"}" onclick="startProgram('${p.id}')">${active?"Active":"Start"}</button></div>`}).join("")}
function startProgram(id){S.activeProgram=id;save();renderPrograms();toast("Program started")}

function startMission(){if(S.mission&&S.mission.ends>Date.now()){toast("Shadow is already on a mission");return}const m=MISSIONS[Math.floor(Math.random()*MISSIONS.length)];S.mission={id:m.id,name:m.name,ends:Date.now()+m.mins*60*1000,coins:m.coins,ess:m.ess,xp:m.xp};save();renderShadow();toast(`Shadow sent on ${m.name}`);system(`Your Shadow left for ${m.name}. Return later for loot.`)}
function claimMission(){if(!S.mission)return;if(Date.now()<S.mission.ends){toast("Mission still in progress");return}const m=S.mission;addXP(m.xp,"Shadow Mission");S.coins+=m.coins;S.essence+=m.ess;S.mission=null;save();render();toast(`Loot claimed · +${m.coins} 🪙 · +${m.ess} ✦`);system(`Shadow returned from ${m.name} with loot.`)}
function renderShadow(){document.getElementById("coinCount").textContent=S.coins||0;document.getElementById("essCount").textContent=S.essence||0;document.getElementById("shadowName").textContent=(S.name?S.name+"'s ":"")+"Shadow";const ctrl=document.getElementById("missionControls");const status=document.getElementById("shadowStatus");if(S.mission){const left=Math.max(0,S.mission.ends-Date.now());if(left>0){const mins=Math.ceil(left/60000);status.textContent=`On mission: ${S.mission.name} (${mins} min left)`;ctrl.innerHTML=`<button class="btn-secondary btn-full" disabled>Mission in progress…</button>`}else{status.textContent=`Returned from ${S.mission.name} — loot ready!`;ctrl.innerHTML=`<button class="btn-success btn-full" onclick="claimMission()">Claim Loot</button>`}}else{status.textContent="Ready for a mission";ctrl.innerHTML=`<button class="btn-primary btn-full" onclick="startMission()">↗ Send Mission</button>`}}

function openAvatarPicker(){const box=document.getElementById("avatarPick");box.innerHTML=AVATARS.map(a=>`<span class="${a===S.avatar?"on":""}" onclick="setAvatar('${a}')">${a}</span>`).join("");document.getElementById("avatarModal").classList.add("show")}
function closeAvatarPicker(){document.getElementById("avatarModal").classList.remove("show")}
function setAvatar(a){S.avatar=a;save();document.getElementById("avatarBtn").textContent=a;openAvatarPicker();toast("Avatar updated")}
function editBio(){const cur=S.bio||"";const n=prompt("Bio (max 80 chars)",cur);if(n===null)return;S.bio=n.slice(0,80);save();renderProfileExtra();toast("Bio updated")}

function expBadge(){const x=S.totalXP||0;if(x>=5000)return"Elite";if(x>=2000)return"Seasoned";if(x>=500)return"Trained";return"Novice"}
function fitnessScore(){const s=S.stats;return Math.min(99,Math.round((s.str+s.end+s.agi+s.vit)/4))}
function activityScore(){const days=Object.keys(S.activity||{}).length;return Math.min(99,Math.round(S.streak*4+days*1.5+S.workouts))}
function fitnessAge(){const p=S.profile||{};const base=18;const adj=((p.strength||2)+(p.mobility||2)+(p.cardio||2)-6)*-1.5;return Math.max(12,Math.round(base+adj+(S.level>10?-2:0)))}

function renderProfileExtra(){
document.getElementById("avatarBtn").textContent=S.avatar||"👤";
const bio=document.getElementById("bioText");
if(S.bio){bio.textContent=S.bio;bio.classList.remove("empty")}else{bio.textContent="Tap to add a bio";bio.classList.add("empty")}
document.getElementById("expBadge").textContent=expBadge();
document.getElementById("fitScore").textContent=fitnessScore();
document.getElementById("actScore").textContent=activityScore();
document.getElementById("fitAge").textContent=fitnessAge();
document.getElementById("expScore").textContent=expBadge();
const p=S.profile||{};
const goalNames={strength:"Get stronger",endurance:"More endurance",skill:"Build skills",balanced:"All-around fit"};
document.getElementById("goalsDash").innerHTML=`Main: <strong>${goalNames[S.goal]||S.goal||"—"}</strong><br>Focus: <strong>${S.weekFocus||"—"}</strong><br>Days/week: <strong>${p.days?p.days+"+":"—"}</strong> · Duration: <strong>${p.duration?p.duration+" min":"—"}</strong>`;
document.getElementById("achGrid").innerHTML=ACHIEVEMENTS.map(a=>{const on=S.achievements.includes(a.id)?"unlocked":"";return `<div class="ach ${on}"><div class="ach-icon">${a.icon}</div><div class="ach-name">${a.name}</div></div>`}).join("");
const favs=[];
if(S.exCount)Object.entries(S.exCount).sort((a,b)=>b[1]-a[1]).slice(0,4).forEach(([n,c])=>favs.push(`<span class="fav-chip">${n} · ${c}</span>`));
if(S.woCount)Object.entries(S.woCount).sort((a,b)=>b[1]-a[1]).slice(0,3).forEach(([n,c])=>favs.push(`<span class="fav-chip">${n} · ${c}×</span>`));
document.getElementById("favList").innerHTML=favs.length?favs.join(""):'<div class="empty">Train more to build favorites</div>';
const hist=document.getElementById("histList");
if(!S.history||!S.history.length)hist.innerHTML='<div class="empty">No history yet</div>';
else hist.innerHTML=S.history.slice(0,12).map(h=>`<div class="hist-row"><span>${h.s}</span><span style="color:#fff;font-weight:600">+${h.x}</span></div>`).join("");
}

function render(){const r=getRank(S.level);document.getElementById("levelNum").textContent=S.level;document.getElementById("xpText").textContent=`${S.xp} / ${xpNeed(S.level)} XP`;document.getElementById("xpFill").style.width=Math.min(100,S.xp/xpNeed(S.level)*100)+"%";document.getElementById("rankPill").textContent=r.rank+"-RANK";
renderShadow();
const doneQ=S.quests.filter(q=>q.done).length;let focus="Complete your Daily Quests";if(doneQ===0)focus="Start with your main ranked workout";else if(doneQ<S.quests.length)focus="Finish remaining Daily Quests";else if(S.weekly&&!S.weekly.done)focus="Push the Weekly Challenge";else focus="Practice a Skill Path or try a Boss Raid";document.getElementById("focusText").textContent=focus;
const recoverBox=document.getElementById("recoverBox");if(S.lastHardDay===today()&&S.workouts>0){recoverBox.style.display="block";document.getElementById("recoverText").textContent="You already trained hard today. Sleep and easy movement help growth."}else if(S.streak>=5&&doneQ===0){recoverBox.style.display="block";document.getElementById("recoverText").textContent="Long streak. Listening to your body is part of getting stronger."}else recoverBox.style.display="none";
document.getElementById("questCount").textContent=doneQ+"/"+S.quests.length;const ql=document.getElementById("questList");ql.innerHTML="";S.quests.forEach(q=>{const d=document.createElement("div");d.className="item"+(q.done?" done":"");d.innerHTML=`<div class="item-row"><div class="item-name">${q.name}</div><div class="item-xp">+${q.xp} XP</div></div><div class="item-desc">${q.desc}</div><div class="item-actions">${q.done?`<button class="btn-secondary" disabled>Done</button>`:q.type==="workout"?`<button class="btn-primary" onclick="openWorkout('${q.wid}')">Start</button><button class="btn-secondary" onclick="completeQuest('${q.id}')">Mark Done</button>`:`<button class="btn-primary" onclick="completeQuest('${q.id}')">Complete</button>`}</div>`;ql.appendChild(d)});
const wb=document.getElementById("weeklyBox");if(S.weekly)wb.innerHTML=`<div class="item ${S.weekly.done?"done":""}"><div class="item-row"><div class="item-name">${S.weekly.name}</div><div class="item-xp">+${S.weekly.xp} XP</div></div><div class="item-desc">${S.weekly.desc}</div><div style="font-size:.8rem;color:var(--muted)">Progress: ${S.weekly.progress||0} / ${S.weekly.need}</div></div>`;else wb.innerHTML="<div class='empty'>No weekly challenge yet</div>";
const st=id=>{document.getElementById(id).innerHTML=`<div class="stat"><div class="stat-label">Strength</div><div class="stat-value">${S.stats.str}</div></div><div class="stat"><div class="stat-label">Endurance</div><div class="stat-value">${S.stats.end}</div></div><div class="stat"><div class="stat-label">Agility</div><div class="stat-value">${S.stats.agi}</div></div><div class="stat"><div class="stat-label">Vitality</div><div class="stat-value">${S.stats.vit}</div></div>`};st("quickStats");st("fullStats");
document.getElementById("lifeStats").innerHTML=`<div class="stat"><div class="stat-label">Total XP</div><div class="stat-value">${S.totalXP}</div></div><div class="stat"><div class="stat-label">Workouts</div><div class="stat-value">${S.workouts}</div></div><div class="stat"><div class="stat-label">Quests</div><div class="stat-value">${S.questsDone}</div></div><div class="stat"><div class="stat-label">Bosses</div><div class="stat-value">${(S.bossCleared||[]).length}</div></div>`;
document.querySelectorAll(".chip").forEach(c=>c.classList.toggle("active",c.dataset.f===S.weekFocus));
const sl=document.getElementById("skillList");sl.innerHTML="";Object.keys(SKILLS).forEach(key=>{const def=SKILLS[key],sk=S.skills[key]||{level:0,practice:0},curL=def.levels[sk.level],next=def.levels[sk.level+1],canAdvance=sk.practice>=def.need&&next;let ladder="";def.levels.forEach((lv,i)=>{let cls="ladder-step";if(i<sk.level)cls+=" done";if(i===sk.level)cls+=" current";ladder+=`<div class="${cls}"><div class="ladder-dot"></div><span>${lv.name}</span></div>`});const div=document.createElement("div");div.className="skill";div.innerHTML=`<div class="skill-top"><div class="skill-name">${def.name}</div><div class="skill-stage">Stage ${sk.level+1}/${def.levels.length}</div></div><div class="ladder">${ladder}</div><div class="skill-tip"><strong>Form</strong> · ${curL.tip}<span class="skill-mistake">${curL.mistake}</span></div><div class="skill-progress">Practice <strong>${sk.practice}</strong> / ${def.need}${canAdvance?" · Ready":""}</div><div style="display:flex;gap:8px"><button class="btn-secondary" style="flex:1" onclick="practiceSkill('${key}')">Log Practice</button>${next?`<button class="btn-primary" style="flex:1" ${canAdvance?"":"disabled"} onclick="skillUp('${key}')">Advance</button>`:""}</div>`;sl.appendChild(div)});
const wl=document.getElementById("workoutList");wl.innerHTML="";WORKOUTS.forEach(w=>{const d=document.createElement("div");d.className="item";d.innerHTML=`<div class="item-row"><div class="item-name">${w.name} <span style="font-size:.7rem;color:var(--faint)">${w.rank}</span></div><div class="item-xp">+${w.xp}</div></div><div class="item-desc">${w.time} · ${w.ex.length} exercises</div><button class="btn-primary" onclick="openWorkout('${w.id}')">Start</button>`;wl.appendChild(d)});
document.getElementById("weeklyChallenge").innerHTML=S.weekly?`<div class="item ${S.weekly.done?"done":""}"><div class="item-row"><div class="item-name">${S.weekly.name}</div><div class="item-xp">+${S.weekly.xp} XP</div></div><div class="item-desc">${S.weekly.desc}</div><div style="margin-top:4px;font-size:.85rem;color:var(--muted)">Progress: ${S.weekly.progress||0} / ${S.weekly.need}</div></div>`:"<div class='empty'>Loading…</div>";
const br=document.getElementById("bossRaid");br.innerHTML="";BOSSES.forEach(b=>{const cleared=S.bossCleared.includes(b.id);const d=document.createElement("div");d.className="item boss";d.innerHTML=`<div class="item-row"><div class="item-name">${b.name}${cleared?' <span class="badge">CLEARED</span>':''}</div><div class="item-xp">+${b.xp}</div></div><div class="item-desc">${b.desc}</div><button class="btn-gold" onclick="openWorkout('${b.id}',true)">${cleared?"Raid Again":"Enter Raid"}</button>`;br.appendChild(d)});
document.getElementById("hunterName").textContent=S.name;document.getElementById("profileLevel").textContent=S.level;document.getElementById("streakNum").textContent=S.streak;document.getElementById("profileRank").textContent=r.rank+"-RANK";document.getElementById("rankTitle").textContent=r.title;
renderPRs();renderCalendar();renderPrograms();renderProfileExtra()}

document.querySelectorAll(".nav-btn").forEach(btn=>{btn.addEventListener("click",()=>{document.querySelectorAll(".nav-btn").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));btn.classList.add("active");document.getElementById("screen-"+btn.dataset.s).classList.add("active")})});
function refreshQuests(){S.quests=[];S.doneToday=[];makeQuests();render();toast("Quests refreshed")}
function exportSave(){const blob=new Blob([JSON.stringify(S,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="arise-"+(S.name||"hunter")+".json";a.click();toast("Exported")}
function resetAll(){if(confirm("Delete all progress?")){localStorage.removeItem("arise_v11");localStorage.removeItem("arise_v10");localStorage.removeItem("arise_v9");location.reload()}}
function init(){if(load()){makeQuests();makeWeekly();document.getElementById("onboard").classList.add("hidden");render();system(`Welcome back, ${S.name}. Rank: ${getRank(S.level).title}.`)}setInterval(renderShadow,30000)}init();
