const EXERCISES=[
{id:'ex_pushup',name:'Push-up',cat:'strength',equip:'bodyweight',diff:2,muscles:'Chest, Triceps, Core',tip:'Hands under shoulders, body straight',mistake:'Hips sagging or flaring elbows',prog:'Knee → Full → Diamond → Archer',reg:'Wall or knee push-ups'},
{id:'ex_squat',name:'Bodyweight Squat',cat:'strength',equip:'bodyweight',diff:1,muscles:'Quads, Glutes',tip:'Sit back, knees track over toes',mistake:'Knees caving in',prog:'Assisted → Full → Jump → Pistol progress',reg:'Chair sit-to-stand'},
{id:'ex_plank',name:'Plank',cat:'strength',equip:'bodyweight',diff:1,muscles:'Core',tip:'Hips level, breathe steadily',mistake:'Hips dropping or piking',prog:'Knee plank → Full → Side → Weighted',reg:'Knee plank'},
{id:'ex_lunge',name:'Forward Lunge',cat:'strength',equip:'bodyweight',diff:2,muscles:'Quads, Glutes',tip:'Front knee over ankle',mistake:'Knee past toes heavily',prog:'Static → Walking → Jump lunges',reg:'Reverse lunge with support'},
{id:'ex_burpee',name:'Burpee',cat:'hiit',equip:'bodyweight',diff:3,muscles:'Full body',tip:'Land soft, jump with control',mistake:'Collapsing on landing',prog:'Step-back → Full → With push-up',reg:'Step-back burpee'},
{id:'ex_jj',name:'Jumping Jacks',cat:'cardio',equip:'bodyweight',diff:1,muscles:'Full body',tip:'Soft landings',mistake:'Locking knees',prog:'Slow → Normal → High tempo',reg:'Step-out jacks'},
{id:'ex_mk',name:'Mountain Climbers',cat:'hiit',equip:'bodyweight',diff:2,muscles:'Core, Cardio',tip:'Hips steady, quick feet',mistake:'Bouncing hips',prog:'Slow → Fast → Cross-body',reg:'Standing high knees'},
{id:'ex_pu_pike',name:'Pike Push-up',cat:'strength',equip:'bodyweight',diff:3,muscles:'Shoulders',tip:'Hips high, head toward floor',mistake:'Elbows flaring wide',prog:'Elevated feet → Freestanding HSPU progress',reg:'Wall-supported pike'},
{id:'ex_diamond',name:'Diamond Push-up',cat:'strength',equip:'bodyweight',diff:3,muscles:'Triceps, Chest',tip:'Hands form diamond under chest',mistake:'Shoulders shrugged',prog:'Close-grip → Diamond → Rings',reg:'Close-grip push-ups'},
{id:'ex_glute',name:'Glute Bridge',cat:'strength',equip:'bodyweight',diff:1,muscles:'Glutes',tip:'Squeeze at top, neutral spine',mistake:'Overarching lower back',prog:'Single-leg → Weighted',reg:'Short-range bridge'},
{id:'ex_hollow',name:'Hollow Hold',cat:'calisthenics',equip:'bodyweight',diff:3,muscles:'Core',tip:'Lower back pressed to floor',mistake:'Arching lower back',prog:'Tuck → Advanced hollow',reg:'Dead bug'},
{id:'ex_au_pull',name:'Australian Pull-up',cat:'calisthenics',equip:'bar',diff:2,muscles:'Back, Biceps',tip:'Chest to bar, body straight',mistake:'Hips sagging',prog:'Higher bar → Lower bar → Pull-ups',reg:'Scapular pulls'},
{id:'ex_pullup',name:'Pull-up',cat:'calisthenics',equip:'bar',diff:4,muscles:'Back, Biceps',tip:'Chin over bar, control down',mistake:'Kipping / swinging',prog:'Negatives → Full → Chest-to-bar',reg:'Australian pull-ups'},
{id:'ex_dip',name:'Bench Dip',cat:'strength',equip:'bench',diff:2,muscles:'Triceps',tip:'Shoulders down, elbows back',mistake:'Shrugging shoulders',prog:'Feet elevated → Parallel bar dips',reg:'Feet close dips'},
{id:'ex_wallsit',name:'Wall Sit',cat:'strength',equip:'bodyweight',diff:2,muscles:'Quads',tip:'Knees at 90°, back flat',mistake:'Knees past toes',prog:'Timed holds → Single-leg',reg:'Higher sit'},
{id:'ex_crunch',name:'Crunch',cat:'strength',equip:'bodyweight',diff:1,muscles:'Abs',tip:'Curl shoulders, do not yank neck',mistake:'Pulling on neck',prog:'Dead bug → Crunch → V-up',reg:'Partial crunch'},
{id:'ex_sideplank',name:'Side Plank',cat:'strength',equip:'bodyweight',diff:2,muscles:'Obliques',tip:'Hips stacked high',mistake:'Rotating or dropping hip',prog:'Knee side plank → Full → Dips',reg:'Knee side plank'},
{id:'ex_hk',name:'High Knees',cat:'cardio',equip:'bodyweight',diff:2,muscles:'Cardio, Legs',tip:'Drive knees up, arms pump',mistake:'Leaning back',prog:'March → High knees → Sprint in place',reg:'Marching in place'},
{id:'ex_jump_squat',name:'Jump Squat',cat:'plyometric',equip:'bodyweight',diff:3,muscles:'Legs, Power',tip:'Land soft into squat',mistake:'Hard stiff landing',prog:'Squat → Jump squat → Tuck jump',reg:'Bodyweight squat'},
{id:'ex_superman',name:'Superman Hold',cat:'mobility',equip:'bodyweight',diff:1,muscles:'Back',tip:'Lift chest and legs gently',mistake:'Overextending neck',prog:'Short holds → Longer',reg:'Prone Y raises'},
{id:'ex_catcow',name:'Cat-Cow',cat:'mobility',equip:'bodyweight',diff:1,muscles:'Spine',tip:'Move with breath',mistake:'Forcing range',prog:'Slow flow → Deeper range',reg:'Seated cat-cow'},
{id:'ex_hamstring',name:'Standing Hamstring Stretch',cat:'stretching',equip:'bodyweight',diff:1,muscles:'Hamstrings',tip:'Hinge at hips, soft knee',mistake:'Rounding upper back hard',prog:'Seated → Standing → Single-leg',reg:'Seated forward fold'},
{id:'ex_hipflex',name:'Hip Flexor Stretch',cat:'stretching',equip:'bodyweight',diff:1,muscles:'Hip flexors',tip:'Tuck pelvis gently',mistake:'Arching lower back',prog:'Half-kneeling → Couch stretch',reg:'Gentle half-kneel'},
{id:'ex_shoulder',name:'Shoulder Openers',cat:'mobility',equip:'bodyweight',diff:1,muscles:'Shoulders',tip:'Slow controlled circles',mistake:'Forcing past comfort',prog:'Passive → Active hangs',reg:'Wall slides'},
{id:'ex_worldgreat',name:"World's Greatest Stretch",cat:'mobility',equip:'bodyweight',diff:2,muscles:'Hips, Thoracic',tip:'Rotate open with breath',mistake:'Collapsing front knee',prog:'Static → Flow',reg:'Half-kneeling twist'},
{id:'ex_run_easy',name:'Easy Run',cat:'running',equip:'none',diff:2,muscles:'Cardio',tip:'Conversational pace',mistake:'Starting too fast',prog:'Walk-run → Continuous',reg:'Brisk walk'},
{id:'ex_walk',name:'Brisk Walk',cat:'walking',equip:'none',diff:1,muscles:'Cardio',tip:'Heel-toe, upright',mistake:'Shuffling feet',prog:'Casual → Brisk → Incline',reg:'Casual walk'},
{id:'ex_cycle',name:'Steady Cycle',cat:'cycling',equip:'bike',diff:2,muscles:'Cardio, Legs',tip:'Smooth cadence',mistake:'Mashing heavy gear',prog:'Easy → Tempo → Intervals',reg:'Easy spin'},
{id:'ex_swim',name:'Easy Swim',cat:'swimming',equip:'pool',diff:2,muscles:'Full body',tip:'Long smooth strokes',mistake:'Holding breath too long',prog:'Kickboard → Full strokes',reg:'Kick drills'},
{id:'ex_shadowbox',name:'Shadow Boxing',cat:'boxing',equip:'bodyweight',diff:2,muscles:'Cardio, Shoulders',tip:'Hands up, light feet',mistake:'Dropping hands',prog:'Jab-cross → Combos → With footwork',reg:'Slow shadow drill'},
{id:'ex_kick',name:'Front Kick Drill',cat:'kickboxing',equip:'bodyweight',diff:2,muscles:'Legs, Core',tip:'Chamber then extend',mistake:'Locking knee hard',prog:'Slow → Snap kicks',reg:'Knee raises'},
{id:'ex_dance',name:'Free Dance Cardio',cat:'dance',equip:'bodyweight',diff:1,muscles:'Cardio',tip:'Keep moving, have fun',mistake:'Stopping between songs',prog:'Low intensity → Continuous',reg:'March in place'},
{id:'ex_yoga_down',name:'Downward Dog',cat:'yoga',equip:'bodyweight',diff:1,muscles:'Hamstrings, Shoulders',tip:'Press floor away',mistake:'Rounded upper back',prog:'Short holds → Longer',reg:'Puppy pose'},
{id:'ex_yoga_warrior',name:'Warrior II',cat:'yoga',equip:'bodyweight',diff:2,muscles:'Legs, Hips',tip:'Front knee over ankle',mistake:'Leaning torso forward',prog:'Short → Longer holds',reg:'High lunge'},
{id:'ex_pilates_hundred',name:'Pilates Hundred',cat:'pilates',equip:'bodyweight',diff:2,muscles:'Core',tip:'Pump arms, steady breath',mistake:'Tensing neck',prog:'Knees bent → Legs long',reg:'Knees bent version'},
{id:'ex_foam',name:'Foam Roll Quads',cat:'recovery',equip:'roller',diff:1,muscles:'Recovery',tip:'Slow rolls, pause on tight spots',mistake:'Rolling too fast on joints',prog:'Short → Full sessions',reg:'Hand massage'},
{id:'ex_deadbug',name:'Dead Bug',cat:'rehabilitation',equip:'bodyweight',diff:1,muscles:'Core',tip:'Press low back down',mistake:'Arching spine',prog:'Arms only → Opposite limbs',reg:'Heel taps'},
{id:'ex_bird',name:'Bird Dog',cat:'rehabilitation',equip:'bodyweight',diff:1,muscles:'Core, Back',tip:'Reach long, stable hips',mistake:'Rotating hips',prog:'Short holds → Longer',reg:'Hands and knees hold'},
{id:'ex_warmup_jj',name:'Warm-up Jacks',cat:'warmups',equip:'bodyweight',diff:1,muscles:'Full body',tip:'Easy pace to raise heart rate',mistake:'Going all-out',prog:'1 min → 2 min',reg:'Marching'},
{id:'ex_cooldown_breathe',name:'Breathing Cool-down',cat:'cooldowns',equip:'bodyweight',diff:1,muscles:'Recovery',tip:'Inhale 4, exhale 6',mistake:'Rushing breaths',prog:'1 min → 3 min',reg:'Seated quiet sit'},
];
const LIBRARY=[
{id:'lib_str1',name:'Foundation Strength',cat:'strength',mins:15,ex:['ex_pushup','ex_squat','ex_plank','ex_glute'],desc:'Build basic strength'},
{id:'lib_str2',name:'Upper Gate',cat:'strength',mins:20,ex:['ex_pushup','ex_diamond','ex_au_pull','ex_dip'],desc:'Upper body focus'},
{id:'lib_str3',name:'Lower Gate',cat:'strength',mins:20,ex:['ex_squat','ex_lunge','ex_glute','ex_wallsit'],desc:'Lower body focus'},
{id:'lib_hiit1',name:'Shadow Burst',cat:'hiit',mins:12,ex:['ex_jj','ex_mk','ex_burpee','ex_jump_squat'],desc:'Short intense intervals'},
{id:'lib_hiit2',name:'Gate Rush',cat:'hiit',mins:18,ex:['ex_burpee','ex_mk','ex_hk','ex_jump_squat'],desc:'Higher volume HIIT'},
{id:'lib_cardio1',name:'Steady Path',cat:'cardio',mins:20,ex:['ex_jj','ex_hk','ex_walk'],desc:'Easy cardio base'},
{id:'lib_run1',name:'Easy Run Session',cat:'running',mins:25,ex:['ex_warmup_jj','ex_run_easy','ex_cooldown_breathe'],desc:'Beginner run'},
{id:'lib_walk1',name:'Walk Protocol',cat:'walking',mins:30,ex:['ex_walk','ex_cooldown_breathe'],desc:'Active recovery walk'},
{id:'lib_yoga1',name:'Morning Flow',cat:'yoga',mins:15,ex:['ex_catcow','ex_yoga_down','ex_yoga_warrior','ex_cooldown_breathe'],desc:'Gentle yoga'},
{id:'lib_mob1',name:'Mobility Gate',cat:'mobility',mins:12,ex:['ex_catcow','ex_worldgreat','ex_shoulder','ex_hipflex'],desc:'Open up stiff areas'},
{id:'lib_stretch1',name:'Full Stretch',cat:'stretching',mins:10,ex:['ex_hamstring','ex_hipflex','ex_shoulder','ex_cooldown_breathe'],desc:'Cool-down stretch'},
{id:'lib_cal1',name:'Calisthenics Path',cat:'calisthenics',mins:25,ex:['ex_pushup','ex_au_pull','ex_hollow','ex_pu_pike'],desc:'Bodyweight skills'},
{id:'lib_box1',name:'Shadow Boxing Round',cat:'boxing',mins:15,ex:['ex_warmup_jj','ex_shadowbox','ex_hk','ex_cooldown_breathe'],desc:'Boxing cardio'},
{id:'lib_kick1',name:'Kick Drill',cat:'kickboxing',mins:15,ex:['ex_hk','ex_kick','ex_shadowbox','ex_plank'],desc:'Kickboxing basics'},
{id:'lib_pilates1',name:'Core Pilates',cat:'pilates',mins:12,ex:['ex_pilates_hundred','ex_deadbug','ex_plank','ex_sideplank'],desc:'Pilates core'},
{id:'lib_dance1',name:'Dance Cardio',cat:'dance',mins:15,ex:['ex_dance','ex_jj','ex_hk'],desc:'Fun cardio'},
{id:'lib_rehab1',name:'Core Stability',cat:'rehabilitation',mins:12,ex:['ex_deadbug','ex_bird','ex_glute','ex_plank'],desc:'Gentle stability'},
{id:'lib_wu1',name:'Standard Warm-up',cat:'warmups',mins:5,ex:['ex_jj','ex_catcow','ex_hk'],desc:'Before training'},
{id:'lib_cd1',name:'Standard Cool-down',cat:'cooldowns',mins:5,ex:['ex_hamstring','ex_hipflex','ex_cooldown_breathe'],desc:'After training'},
{id:'lib_rec1',name:'Recovery Session',cat:'recovery',mins:10,ex:['ex_foam','ex_catcow','ex_cooldown_breathe'],desc:'Easy recovery day'},
];
